# -*- coding: utf-8 -*-
"""shape_module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10U5q5VPhJ5NlqaV7RnMupUR9gz3JAw07
"""

def get_circle_area(radius):
  return 22/7 * (radius** 2)

def get_triangle_area(width,height):
  return 1/2 * width * height

def get_rectangle_area(width,height):
  return width * height